In [13]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [14]:
space_data = pd.read_csv("train.csv")
data = space_data
data.head(10)


PassengerId HomePlanet CryoSleep  Cabin    Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P    TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S    TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S    TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S    TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S    TRAPPIST-1e  16.0  False   
5     0005_01      Earth     False  F/0/P  PSO J318.5-22  44.0  False   
6     0006_01      Earth     False  F/2/S    TRAPPIST-1e  26.0  False   
7     0006_02      Earth      True  G/0/S    TRAPPIST-1e  28.0  False   
8     0007_01      Earth     False  F/3/S    TRAPPIST-1e  35.0  False   
9     0008_01     Europa      True  B/1/P    55 Cancri e  14.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck                Name  \
0          0.0        0.0           0.0     0.0     0.0     Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0        Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0       Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0        Solam Susent   
4        303.0       70.0         151.0   565.0     2.0   Willy Santantines   
5          0.0      483.0           0.0   291.0     0.0   Sandie Hinetthews   
6         42.0     1539.0           3.0     0.0     0.0  Billex Jacostaffey   
7          0.0        0.0           0.0     0.0     NaN  Candra Jacostaffey   
8          0.0      785.0          17.0   216.0     0.0       Andona Beston   
9          0.0        0.0           0.0     0.0     0.0      Erraiam Flatic   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True  
5         True  
6         True  
7         True  
8         True  
9         True

In [15]:
data.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='object')

In [16]:
pd.crosstab(data.Age,data.Transported)

Transported  False  True
Age                     
0.0             34   144
1.0             18    49
2.0             22    53
3.0             16    59
4.0             18    53
...            ...   ...
75.0             2     2
76.0             1     1
77.0             1     1
78.0             2     1
79.0             3     0

[80 rows x 2 columns]

In [17]:
data.Transported.unique()

array([False,  True])

In [19]:
data.Transported = LabelEncoder().fit_transform(data.Transported)
data.Transported.unique()

array([0, 1], dtype=int64)

In [25]:
data.CryoSleep.unique()
data.CryoSleep.value_counts()

0    5439
1    3037
2     217
Name: CryoSleep, dtype: int64

In [27]:
data.CryoSleep = LabelEncoder().fit_transform(data.CryoSleep)
data.CryoSleep.unique()

array([0, 1, 2], dtype=int64)